from conjuntoABB import *

A=leer('Alumnos del curso A:','.')
B=leer('Alumnos del curso B:','.')
C=leer('Alumnos del curso C:','.')
c=inter(B,C)
d=inter(A,C)
e=resta(union(union(A,B),C),inter(A,B))
f=resta(e,c)
g=resta(f,d)
print('Alumnos en solo 1 curso:')
escribir(g)
print()
print('Alumnos en solo 2 cursos:')
escribir(resta(union(union(inter(A,B),inter(B,C)),inter(A,C)),inter(inter(A,B),C)))
print()
print('Alumnos en los 3 cursos (simultaneamente):')
escribir(inter(inter(A,B),C))
print()
print('Alumnos en algun curso:')
escribir(union(union(A,B),C))